version: '3.1'
# docker-compose up -d
services:

  db:
    image: mysql:8.0.28-oracle
    networks:
      - app
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3310:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysqlVol:/var/lib/mysql
  user-service:
    build: .
    networks:
      - app
    depends_on:
      - db  
    ports:
      - "8080:8080"    

volumes:
 mysqlVol:
 
networks:
  app:
    driver: bridge 